---
abstract: 'Fetch real time stock quotes from nasdaq.com'
author:
  - 'Ian Kilgore <iank@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-NASDAQ-Quote
no_index:
  directory:
    - t
    - inc
requires:
  HTML::TreeBuilder: 0
  LWP::Simple: 0
  Test::More: 0
  URI: 0
version: 0.07
